runtime: nodejs14

automatic_scaling:
  target_cpu_utilization: 0.65

handlers:
- url: /
  static_files: build/index.html
  upload: build/index.html

- url: /(.*)
  static_files: build/\1
  upload: build/(.*)
